name: Deploy PR

on: 
  pull_request:
    types: [ opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: clone
      run: |
        echo ${{ github.ref }}
        git clone  https://github.com/jihuayu/FZU-OOP-2020.git dist
        cd dist
        git checkout -b gh-pages origin/gh-pages
        shopt -s extglob 
        number=$(echo ${{ github.ref }} | sed 's/refs\/pull\/\([0-9]*\)\/merge/\1/g')
        mkdir -p pr/${number}
        cd pr/${number}
        rm -fr *
        cd ..
    - name: npm install, build
      run: |
        npm i
        number=$(echo ${{ github.ref }} | sed 's/refs\/pull\/\([0-9]*\)\/merge/\1/g')
        export BASE_URL=/pr/${number}/
        npm run build
    - name: copy 
      run: |
        number=$(echo ${{ github.ref }} | sed 's/refs\/pull\/\([0-9]*\)\/merge/\1/g')
        cp -r ./docs/.vuepress/dist/* dist/pr/${number}/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.push }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: dist

